name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: devkitpro/devkitarm:latest

    steps:
      - name: "Clone"
        run: git clone --recurse-submodules -j8 https://github.com/seien210300928/Checkpoint_Chs.git /Checkpoint_Chs
      - name: "Build"
        working-directory: "/Checkpoint_Chs"
        run: |
          make
          zip -r Checkpoint_Chs.zip 3ds/out/Checkpoint.cia 3ds/out/Checkpoint.3dsx 3ds/out/Checkpoint.elf
      - uses: actions/upload-artifact@v4
        with:
          name: Checkpoint_Chs-Build
          path: /Checkpoint_Chs.zip